# Generated by Django 4.2.3 on 2025-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(max_length=64)),
                ('name', models.TextField(max_length=64)),
                ('phone', models.TextField(max_length=11)),
                ('item', models.TextField(max_length=64)),
                ('count', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('status', models.CharField(choices=[('pick', 'Pick'), ('unpick', 'Unpick'), ('busy', 'Busy'), ('unconnect', 'Unconnect')], max_length=20)),
                ('taken', models.BooleanField(default=False)),
                ('receiveDate', models.DateField()),
            ],
        ),
    ]
