# Generated by Django 4.2.3 on 2025-02-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('takenTime', models.DateTimeField()),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to='parcel.parcel')),
            ],
        ),
    ]
