# Generated by Django 4.2.3 on 2025-02-01 14:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_taker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MM'),
        ),
    ]
